version: "3"

services:
  node:
    image: node:latest
    working_dir: /app
    volumes:
      - ./:/app
    container_name: trybetunes_api
    tty: true
    stdin_open: true
    command: bash
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - $API_PORT:$API_PORT
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - JWT_SECRET=$JWT_SECRET
  db:
    container_name: trybetunes_db
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - $DB_PORT:$DB_PORT
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD

networks:
  default:
    name: trybe_tunes